del ALL_BUILD.vcxproj
del ALL_BUILD.vcxproj.filters
del ALL_BUILD.vcxproj.user
del CMakeCache.txt
del RecorderDll.sln
del RecorderDll.vcxproj
del RecorderDll.vcxproj.filters
del RecorderDll.vcxproj.user
del ZERO_CHECK.vcxproj
del ZERO_CHECK.vcxproj.filters
del ZERO_CHECK.vcxproj.user
